language: python
sudo: required
dist: trusty
os: linux

matrix:
  include:
    - name "Linux / Python 3.6"
      python: 3.6
    - name "Linux / Python 3.7"
      python: 3.7
    - name "OSX / Python 3.6"
      os: osx
      language: generic
      env: PYTHON=3.6.3
    - name "OSX / Python 3.7"
      os: osx
      language: generic
      env: PYTHON=3.7.4

addons:
  apt:
    update: true
    packages:
      - hdf5-tools

# https://pythonhosted.org/CodeChat/.travis.yml.html
before_install:
  - linux() { if test "$TRAVIS_OS_NAME" == "linux"; then $@; fi; }
  - osx() { if test "$TRAVIS_OS_NAME" == "osx"; then $@; fi; }
  - osx brew update
  - osx rm -vf /usr/local/include/c++
  - osx brew install gcc
  - osx brew install hdf5
  - osx brew install lzo
  - osx brew outdated pyenv || brew upgrade pyenv
  - osx brew install pyenv-virtualenv
  - osx pyenv install $PYTHON
  - osx export MPLBACKEND="tkagg"
  - osx export PYENV_VERSION=$PYTHON
  - osx export PATH="/Users/travis/.pyenv/shims:${PATH}"
  - osx pyenv virtualenv venv
  - osx . /Users/travis/.pyenv/versions/$PYTHON/envs/venv/bin/activate
  - python --version
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install --upgrade pip
  - pip install --upgrade setuptools

install:
  - make develop

script:
  - python -c 'import superdatabase3000'
  - make flake
  - make lint
  - make test
  - make coverage
  - make todo

after_script:
  - make uninstall
  - make install
  - make reinstall
  - make doc
  - make clean
